files:

  analysis:
    analysis_c417/3dvar_c417.fv_core.res.nc

  background:
    Data/inputs/lam_c417/bkg/20201215.000000.rrfs_C417.fv_core.res.tile1.nc

  obs:
    analysis_c417/obs/aircraft_diagnostics.nc4

  grid:
    Data/inputs/lam_c417/INPUT/C417_grid.tile7.halo3.nc

plot:

  var: T

  level: -1

  region:
    - -100
    - -60
    - 25
    - 50

  output_pdf:
    c417_3dvar_diagnostics.pdf

density:

  bandwidth: 1.2

  points: 500